import 'package:flutter/material.dart';
import '../../../shared/models/food_model.dart';

class FoodSearchScreen extends StatelessWidget {
  const FoodSearchScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final List<Food> foodList = [
      Food(
        id: "apple",
        name: "Apple",
        category: "Fruit",
        caloriesPerGram: 0.52,
        proteinPerGram: 0.003,
        carbsPerGram: 0.14,
        fatPerGram: 0.002,
      ),
      Food(
        id: "banana",
        name: "Banana",
        category: "Fruit",
        caloriesPerGram: 0.89,
        proteinPerGram: 0.011,
        carbsPerGram: 0.23,
        fatPerGram: 0.003,
      ),
      Food(
        id: "orange",
        name: "Orange",
        category: "Fruit",
        caloriesPerGram: 0.47,
        proteinPerGram: 0.009,
        carbsPerGram: 0.12,
        fatPerGram: 0.001,
      ),
      Food(
        id: "strawberry",
        name: "Strawberry",
        category: "Fruit",
        caloriesPerGram: 0.32,
        proteinPerGram: 0.007,
        carbsPerGram: 0.08,
        fatPerGram: 0.003,
      ),
      Food(
        id: "grapes",
        name: "Grapes",
        category: "Fruit",
        caloriesPerGram: 0.69,
        proteinPerGram: 0.007,
        carbsPerGram: 0.18,
        fatPerGram: 0.002,
      ),
      Food(
        id: "watermelon",
        name: "Watermelon",
        category: "Fruit",
        caloriesPerGram: 0.30,
        proteinPerGram: 0.006,
        carbsPerGram: 0.08,
        fatPerGram: 0.002,
      ),
      Food(
        id: "mango",
        name: "Mango",
        category: "Fruit",
        caloriesPerGram: 0.60,
        proteinPerGram: 0.008,
        carbsPerGram: 0.15,
        fatPerGram: 0.004,
      ),
      Food(
        id: "pineapple",
        name: "Pineapple",
        category: "Fruit",
        caloriesPerGram: 0.50,
        proteinPerGram: 0.005,
        carbsPerGram: 0.13,
        fatPerGram: 0.001,
      ),
      
      // Vegetables
      Food(
        id: "broccoli",
        name: "Broccoli",
        category: "Vegetable",
        caloriesPerGram: 0.34,
        proteinPerGram: 0.028,
        carbsPerGram: 0.07,
        fatPerGram: 0.003,
      ),
      Food(
        id: "spinach",
        name: "Spinach",
        category: "Vegetable",
        caloriesPerGram: 0.23,
        proteinPerGram: 0.029,
        carbsPerGram: 0.04,
        fatPerGram: 0.004,
      ),
      Food(
        id: "carrot",
        name: "Carrot",
        category: "Vegetable",
        caloriesPerGram: 0.41,
        proteinPerGram: 0.009,
        carbsPerGram: 0.10,
        fatPerGram: 0.002,
      ),
      Food(
        id: "tomato",
        name: "Tomato",
        category: "Vegetable",
        caloriesPerGram: 0.18,
        proteinPerGram: 0.009,
        carbsPerGram: 0.04,
        fatPerGram: 0.002,
      ),
      Food(
        id: "cucumber",
        name: "Cucumber",
        category: "Vegetable",
        caloriesPerGram: 0.15,
        proteinPerGram: 0.007,
        carbsPerGram: 0.04,
        fatPerGram: 0.001,
      ),
      Food(
        id: "lettuce",
        name: "Lettuce",
        category: "Vegetable",
        caloriesPerGram: 0.15,
        proteinPerGram: 0.014,
        carbsPerGram: 0.03,
        fatPerGram: 0.002,
      ),
      Food(
        id: "sweetPotato",
        name: "Sweet Potato",
        category: "Vegetable",
        caloriesPerGram: 0.86,
        proteinPerGram: 0.016,
        carbsPerGram: 0.20,
        fatPerGram: 0.003,
      ),
      Food(
        id: "bell_pepper",
        name: "Bell Pepper",
        category: "Vegetable",
        caloriesPerGram: 0.31,
        proteinPerGram: 0.010,
        carbsPerGram: 0.06,
        fatPerGram: 0.003,
      ),
      
      // Grains
      Food(
        id: "rice",
        name: "White Rice (cooked)",
        category: "Grain",
        caloriesPerGram: 1.3,
        proteinPerGram: 0.026,
        carbsPerGram: 0.28,
        fatPerGram: 0.003,
      ),
      Food(
        id: "brown_rice",
        name: "Brown Rice (cooked)",
        category: "Grain",
        caloriesPerGram: 1.12,
        proteinPerGram: 0.026,
        carbsPerGram: 0.23,
        fatPerGram: 0.009,
      ),
      Food(
        id: "pasta",
        name: "Pasta (cooked)",
        category: "Grain",
        caloriesPerGram: 1.31,
        proteinPerGram: 0.051,
        carbsPerGram: 0.25,
        fatPerGram: 0.009,
      ),
      Food(
        id: "bread",
        name: "Whole Wheat Bread",
        category: "Grain",
        caloriesPerGram: 2.47,
        proteinPerGram: 0.13,
        carbsPerGram: 0.41,
        fatPerGram: 0.032,
      ),
      Food(
        id: "oats",
        name: "Oats (cooked)",
        category: "Grain",
        caloriesPerGram: 0.71,
        proteinPerGram: 0.024,
        carbsPerGram: 0.12,
        fatPerGram: 0.014,
      ),
      Food(
        id: "quinoa",
        name: "Quinoa (cooked)",
        category: "Grain",
        caloriesPerGram: 1.20,
        proteinPerGram: 0.043,
        carbsPerGram: 0.21,
        fatPerGram: 0.019,
      ),
      
      // Proteins
      Food(
        id: "chickenBreast",
        name: "Chicken Breast",
        category: "Protein",
        caloriesPerGram: 1.65,
        proteinPerGram: 0.31,
        carbsPerGram: 0.0,
        fatPerGram: 0.04,
      ),
      Food(
        id: "salmon",
        name: "Salmon",
        category: "Protein",
        caloriesPerGram: 2.08,
        proteinPerGram: 0.20,
        carbsPerGram: 0.0,
        fatPerGram: 0.13,
      ),
      Food(
        id: "tuna",
        name: "Tuna",
        category: "Protein",
        caloriesPerGram: 1.32,
        proteinPerGram: 0.30,
        carbsPerGram: 0.0,
        fatPerGram: 0.01,
      ),
      Food(
        id: "beef",
        name: "Lean Beef",
        category: "Protein",
        caloriesPerGram: 2.50,
        proteinPerGram: 0.26,
        carbsPerGram: 0.0,
        fatPerGram: 0.15,
      ),
      Food(
        id: "pork",
        name: "Pork Loin",
        category: "Protein",
        caloriesPerGram: 2.42,
        proteinPerGram: 0.27,
        carbsPerGram: 0.0,
        fatPerGram: 0.14,
      ),
      Food(
        id: "egg",
        name: "Egg",
        category: "Protein",
        caloriesPerGram: 1.55,
        proteinPerGram: 0.13,
        carbsPerGram: 0.01,
        fatPerGram: 0.11,
      ),
      Food(
        id: "tofu",
        name: "Tofu",
        category: "Protein",
        caloriesPerGram: 0.76,
        proteinPerGram: 0.08,
        carbsPerGram: 0.02,
        fatPerGram: 0.05,
      ),
      
      // Dairy
      Food(
        id: "milk",
        name: "Whole Milk",
        category: "Dairy",
        caloriesPerGram: 0.61,
        proteinPerGram: 0.033,
        carbsPerGram: 0.05,
        fatPerGram: 0.033,
      ),
      Food(
        id: "yogurt",
        name: "Greek Yogurt",
        category: "Dairy",
        caloriesPerGram: 0.59,
        proteinPerGram: 0.10,
        carbsPerGram: 0.04,
        fatPerGram: 0.004,
      ),
      Food(
        id: "cheese",
        name: "Cheddar Cheese",
        category: "Dairy",
        caloriesPerGram: 4.03,
        proteinPerGram: 0.25,
        carbsPerGram: 0.01,
        fatPerGram: 0.33,
      ),
      Food(
        id: "cottage_cheese",
        name: "Cottage Cheese",
        category: "Dairy",
        caloriesPerGram: 0.98,
        proteinPerGram: 0.11,
        carbsPerGram: 0.03,
        fatPerGram: 0.04,
      ),
      
      // Nuts & Seeds
      Food(
        id: "almonds",
        name: "Almonds",
        category: "Nuts",
        caloriesPerGram: 5.76,
        proteinPerGram: 0.21,
        carbsPerGram: 0.22,
        fatPerGram: 0.50,
      ),
      Food(
        id: "walnuts",
        name: "Walnuts",
        category: "Nuts",
        caloriesPerGram: 6.54,
        proteinPerGram: 0.15,
        carbsPerGram: 0.14,
        fatPerGram: 0.65,
      ),
      Food(
        id: "peanuts",
        name: "Peanuts",
        category: "Nuts",
        caloriesPerGram: 5.67,
        proteinPerGram: 0.26,
        carbsPerGram: 0.16,
        fatPerGram: 0.49,
      ),
      Food(
        id: "cashews",
        name: "Cashews",
        category: "Nuts",
        caloriesPerGram: 5.53,
        proteinPerGram: 0.18,
        carbsPerGram: 0.30,
        fatPerGram: 0.44,
      ),
      Food(
        id: "peanut_butter",
        name: "Peanut Butter",
        category: "Nuts",
        caloriesPerGram: 5.88,
        proteinPerGram: 0.25,
        carbsPerGram: 0.20,
        fatPerGram: 0.50,
      ),
      Food(
        id: "chia_seeds",
        name: "Chia Seeds",
        category: "Seeds",
        caloriesPerGram: 4.86,
        proteinPerGram: 0.17,
        carbsPerGram: 0.42,
        fatPerGram: 0.31,
      ),
      
      // Fats & Oils
      Food(
        id: "avocado",
        name: "Avocado",
        category: "Fruit",
        caloriesPerGram: 1.6,
        proteinPerGram: 0.02,
        carbsPerGram: 0.09,
        fatPerGram: 0.15,
      ),
      Food(
        id: "olive_oil",
        name: "Olive Oil",
        category: "Oil",
        caloriesPerGram: 8.84,
        proteinPerGram: 0.0,
        carbsPerGram: 0.0,
        fatPerGram: 1.0,
      ),
      
      // Legumes
      Food(
        id: "lentils",
        name: "Lentils (cooked)",
        category: "Legume",
        caloriesPerGram: 1.16,
        proteinPerGram: 0.09,
        carbsPerGram: 0.20,
        fatPerGram: 0.004,
      ),
      Food(
        id: "chickpeas",
        name: "Chickpeas (cooked)",
        category: "Legume",
        caloriesPerGram: 1.64,
        proteinPerGram: 0.09,
        carbsPerGram: 0.27,
        fatPerGram: 0.03,
      ),
      Food(
        id: "black_beans",
        name: "Black Beans (cooked)",
        category: "Legume",
        caloriesPerGram: 1.32,
        proteinPerGram: 0.09,
        carbsPerGram: 0.24,
        fatPerGram: 0.005,
      ),
      Food(
        id: "kidney_beans",
        name: "Kidney Beans (cooked)",
        category: "Legume",
        caloriesPerGram: 1.27,
        proteinPerGram: 0.09,
        carbsPerGram: 0.23,
        fatPerGram: 0.005,
      ),
      
      // Snacks & Extras
      Food(
        id: "dark_chocolate",
        name: "Dark Chocolate (70%)",
        category: "Snack",
        caloriesPerGram: 5.98,
        proteinPerGram: 0.08,
        carbsPerGram: 0.46,
        fatPerGram: 0.43,
      ),
      Food(
        id: "honey",
        name: "Honey",
        category: "Sweetener",
        caloriesPerGram: 3.04,
        proteinPerGram: 0.003,
        carbsPerGram: 0.82,
        fatPerGram: 0.0,
      ),
      Food(
        id: "protein_powder",
        name: "Whey Protein Powder",
        category: "Supplement",
        caloriesPerGram: 4.0,
        proteinPerGram: 0.80,
        carbsPerGram: 0.05,
        fatPerGram: 0.05,
      ),
    ];

    return Scaffold(
      appBar: AppBar(title: const Text("Search Food")),
      body: ListView.builder(
        itemCount: foodList.length,
        itemBuilder: (_, index) {
          final food = foodList[index];
          return ListTile(
            title: Text(food.name),
            subtitle: Text("${(food.caloriesPerGram * 100).toStringAsFixed(0)} kcal / 100g"),
            onTap: () {
              Navigator.pop(context, food);
            },
          );
        },
      ),
    );
  }
}
